# 回帰分析

Pythonで利用するモジュールの読み込み

In [2]:
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from statsmodels.sandbox.regression.predstd import wls_prediction_std

乱数の初期化

In [4]:
np.random.seed(9876789)

データの生成

In [5]:
nsample = 100
print(nsample)
#
x = np.linspace(0, 10, 100)
X = np.column_stack((x, x**2))
# model parameter
beta = np.array([1, 0.1, 10])
e = np.random.normal(size=nsample)
#
X = sm.add_constant(X)
y = np.dot(X, beta) + e

100


モデルの当てはめ（最小二乗法）と結果の表示

In [6]:
model = sm.OLS(y, X)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.020e+06
Date:                Sun, 20 Jun 2021   Prob (F-statistic):          2.83e-239
Time:                        19:06:21   Log-Likelihood:                -146.51
No. Observations:                 100   AIC:                             299.0
Df Residuals:                      97   BIC:                             306.8
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.3423      0.313      4.292      0.000       0.722       1.963
x1            -0.0402      0.145     -0.278      0.781      -0.327       0.247
x2            10.0103      0.014    715.745      0.000       9.982      10.038
==============================================================================
Omnibus:                        2.042   Durbin-Watson:                   2.274
Prob(Omnibus):                  0.360   Jarque-Bera (JB):                1.875
Skew:                           0.234   Prob(JB):                        0.392
Kurtosis:                       2.519   Cond. No.                         144.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [7]:
print('X\n', X)

X
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00000000e+00 1.01010101e-01 1.02030405e-02]
 [1.00000000e+00 2.02020202e-01 4.08121620e-02]
 [1.00000000e+00 3.03030303e-01 9.18273646e-02]
 [1.00000000e+00 4.04040404e-01 1.63248648e-01]
 [1.00000000e+00 5.05050505e-01 2.55076013e-01]
 [1.00000000e+00 6.06060606e-01 3.67309458e-01]
 [1.00000000e+00 7.07070707e-01 4.99948985e-01]
 [1.00000000e+00 8.08080808e-01 6.52994592e-01]
 [1.00000000e+00 9.09090909e-01 8.26446281e-01]
 [1.00000000e+00 1.01010101e+00 1.02030405e+00]
 [1.00000000e+00 1.11111111e+00 1.23456790e+00]
 [1.00000000e+00 1.21212121e+00 1.46923783e+00]
 [1.00000000e+00 1.31313131e+00 1.72431385e+00]
 [1.00000000e+00 1.41414141e+00 1.99979594e+00]
 [1.00000000e+00 1.51515152e+00 2.29568411e+00]
 [1.00000000e+00 1.61616162e+00 2.61197837e+00]
 [1.00000000e+00 1.71717172e+00 2.94867871e+00]
 [1.00000000e+00 1.81818182e+00 3.30578512e+00]
 [1.00000000e+00 1.91919192e+00 3.68329762e+00]
 [1.00000000e+00 2.02020202e+00 4.081

In [8]:
print('y\n', y)

y
 [1.59484106e-01 2.70962667e+00 1.89386568e+00 1.44041774e+00
 5.60719622e+00 4.01415960e+00 3.79042816e+00 5.49896267e+00
 7.93934063e+00 9.31871940e+00 1.16151797e+01 1.30800908e+01
 1.65916731e+01 1.90612419e+01 2.22779839e+01 2.22973772e+01
 2.90728303e+01 2.95174936e+01 3.43906010e+01 3.68997190e+01
 4.15314299e+01 4.65124798e+01 4.87622029e+01 5.54649378e+01
 6.03995721e+01 6.68905550e+01 7.10273234e+01 7.57840504e+01
 8.32307851e+01 8.80067872e+01 9.24604592e+01 1.00869036e+02
 1.05000770e+02 1.13078878e+02 1.18651097e+02 1.26357451e+02
 1.32682080e+02 1.39131512e+02 1.47437302e+02 1.56109386e+02
 1.64097051e+02 1.73688174e+02 1.81821259e+02 1.88890813e+02
 1.99352099e+02 2.10227715e+02 2.16641136e+02 2.28077202e+02
 2.37086627e+02 2.45435044e+02 2.56253216e+02 2.66268455e+02
 2.77388427e+02 2.88835852e+02 2.97996070e+02 3.11225764e+02
 3.20222632e+02 3.34500736e+02 3.44501923e+02 3.54912182e+02
 3.69614763e+02 3.79619250e+02 3.91610439e+02 4.07712238e+02
 4.19465289e+02 4.325

In [9]:
print('Model Parameters: ', beta)
print('Estimated Parameters: ', results.params)
print('R2: ', results.rsquared)

Model Parameters:  [ 1.   0.1 10. ]
Estimated Parameters:  [ 1.34233516 -0.04024948 10.01025357]
R2:  0.9999879365025871


In [10]:
yest = X.dot(results.params)

In [11]:
print('Estimated y\n', yest)

Estimated y
 [   1.34233516    1.44040458    1.74274404    2.24935355    2.9602331
    3.87538271    4.99480235    6.31849204    7.84645178    9.57868156
   11.51518139   13.65595126   16.00099118   18.55030114   21.30388115
   24.2617312    27.4238513    30.79024145   34.36090164   38.13583187
   42.11503215   46.29850248   50.68624285   55.27825327   60.07453373
   65.07508424   70.27990479   75.68899539   81.30235603   87.11998672
   93.14188746   99.36805824  105.79849906  112.43320993  119.27219085
  126.31544181  133.56296282  141.01475387  148.67081497  156.53114611
  164.5957473   172.86461853  181.33775981  190.01517113  198.8968525
  207.98280392  217.27302538  226.76751688  236.46627843  246.36931003
  256.47661167  266.78818336  277.30402509  288.02413687  298.94851869
  310.07717056  321.41009247  332.94728443  344.68874643  356.63447848
  368.78448058  381.13875272  393.69729491  406.46010714  419.42718941
  432.59854174  445.9741641   459.55405651  473.33821897  487.3266

In [12]:
err = y - yest
print('Errors\n', err)

Errors
 [-1.18285105  1.2692221   0.15112164 -0.80893581  2.64696311  0.13877689
 -1.20437419 -0.81952938  0.09288885 -0.25996216  0.09999829 -0.57586046
  0.5906819   0.5109408   0.9741027  -1.96435398  1.64897896 -1.27274788
  0.02969939 -1.23611283 -0.58360229  0.21397729 -1.92403992  0.18668453
  0.32503836  1.81547076  0.74741861  0.09505498  1.9284291   0.88680045
 -0.68142823  1.50097759 -0.79772941  0.64566773 -0.6210938   0.04200869
 -0.88088288 -1.88324179 -1.23351266 -0.42175965 -0.49869596  0.82355507
  0.48349905 -1.12435863  0.45524641  2.24491068 -0.63188927  1.30968522
  0.62034904 -0.9342657  -0.22339567 -0.51972812  0.08440215  0.81171533
 -0.95244878  1.14859323 -1.18746022  1.55345122 -0.18682311 -1.72229604
  0.8302823  -1.51950308 -2.08685638  1.25213088  0.03810008 -0.06396395
  1.00457685 -0.18437205 -0.73779302 -0.38995562 -0.31341699  0.3326478
 -0.14215366  0.76139018  1.77885289  0.27148382 -1.07522331 -0.92954357
 -0.47597259  0.03591816 -0.13346739  1.4981

In [13]:
mse = sum(err ** 2)/len(err)
print('Mean Squared Errors =', mse)

Mean Squared Errors = 1.0967684007408425
